# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: OnesWay's Blog

description: OnesWay's Blog
baseurl: /
author:
  name: Ben Li
  email: admin@onesway.xyz
  github: jmeviler
  twitter:
  pinterest:
  linkedin:
  bio: 一些人,一些事.
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: about.html
categories_path: categories.html
tags_path: tags.html
about_path: about.html
logo_file: cloudlogo.png
about_file: about.html
BASE_PATH:
